export { default as Header } from './Header/Header'
export { default as GameBoard } from './GameBoard/GameBoard'
export { default as Footer } from './Footer/Footer'
export { default as RulesModal } from './RulesModal/RulesModal'
export { default as SelectionBoard } from './SelectionBoard/SelectionBoard'
export { default as Result } from './Result/Result'
